# dockerfile
FROM golang:1.22 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .

# build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app main.go

# runtime
FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=builder /app /app/server
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/app/server"]