services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db"]
      interval: 3s
      timeout: 3s
      retries: 20
  api:
    build: .
    container_name: go
    environment:
      APP_PORT: "8080"
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: db
      DB_USER: user
      DB_PASSWORD: pass
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: